language: objective-c
before_install:
	- brew update
	- brew reinstall xctool
	- gem update cocoapods
xcode_workspace: CatDetailViewController.xcworkspace
xcode_scheme: CatDetailViewController
xcode_sdk:
	- iphonesimulator
	- iphonesimulator8.1